### ISSUE TITLE
Error in login

### ISSUE THREAD

**Issue by VibhuGautam** [JavatechWorld/BusReservationComplete#1]
I'm getting an error as whenever I tried to login it's showing me : 
"This application has no explicit mapping for /error, so you are seeing this as a fallback." 

![Screenshot_83](https://user-images.githubusercontent.com/49740727/195577843-82523c77-1150-4590-9372-157f93e3acae.png)

**Comment by JavatechWorld** [comment]
Hi, please can you share the screenshot of your ide's console or your server console when you try to login what error is there on the console

**Comment by JavatechWorld** [comment]
@VibhuGautam can you attach the screenshot of console of either you ide or any server logs. So that i can see what error you get while logging in.

**Comment by JavatechWorld** [comment]
I think the issue is resolved . As no Update Marking it Resolved

**Comment by JavatechWorld** [comment]
I think the issue is resolved . As no Update Marking it Resolved
